### ISSUE TITLE
Unnecessary dependency on obsolete package - "mypy-lang"?

### ISSUE THREAD

**Issue by serjinio** [dbrattli/OSlash#15]
The mypy-lang package was obsoleted: https://pypi.org/project/mypy-lang/ and seemingly it not necessary for runtime operation of the oslash. 
Can this dependency be removed as when mypy is installed with obsoleted mypy-lang, then mypy does not run because of conflict with old mypy-lang.

**Comment by dbrattli** [comment]
Should be fixed. Please reopen if you still have problems with the dependencies.
